% up-wind scheme
clc; clf; clear;
xmin = 0; xmax = 2; ymin = 0; ymax = 2.0;
tx(xmin,xmax,ymin,ymax);
figure(1);
set(gca,'FontSize',16);
for i = 1:1:3
    point_line(i*0.5,i*0.5,ymin,ymax);
end
for i = 1:1:3
    point_line(xmin,xmax,i*0.5,i*0.5);
end
for i =1:1:3
    pointk(0.5*i,1,40);
end
pointr(1,1.5,40);
[xp1,yp1]=xy_change(0.35,1.0,xmin,xmax,ymin,ymax);
str_1 = '$k-1,n$';
text('string',str_1,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp1 yp1]);
[xp2,yp2]=xy_change(0.9,1.0,xmin,xmax,ymin,ymax);
str_2 = '$k,n$';
text('string',str_2,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp2 yp2]);
[xp3,yp3]=xy_change(1.35,1.0,xmin,xmax,ymin,ymax);
str_3 = '$k+1,n$';
text('string',str_3,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp3 yp3]);
[xp4,yp4]=xy_change(0.9,1.4,xmin,xmax,ymin,ymax);
str_4 = '$k,n+1$';
text('string',str_4,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp4 yp4]);
%text(0.2,-0.3,'图6.1-1 迎风格式示意图','FontSize',16);
ARROW([0.5 1.1],[0.8 1.1],20,'BaseAngle',60);
ARROW([1.5 1.1],[1.2 1.1],20,'BaseAngle',60);
axis([xmin xmax ymin-0.2 ymax]);              % 注意将y范围扩大0.2
axis off;

