% 蒲丰投针计算\pi示意图
clc; clf; clear;
hold on;
a = pi-0.4; l = 0.7*a;
sita = pi/3;
x0 = l*cos(sita); y0 = l*sin(sita);
xmin = -pi; xmax = pi; ymin = -0.3; ymax = pi-0.4;
axis([xmin xmax+0.3 ymin ymax]);
tx(0,xmax+0.2,ymin+0.3,ymax);
line([-pi -0.5],[0 0]);
line([-pi -0.5],[a a]);
arrow([-pi+0.2 pi/2],[-pi+0.2 a]);
arrow([-pi+0.2 pi/2-0.4],[-pi+0.2 0]);
line([0 pi],[pi/2-0.2 pi/2-0.2]);
line([pi pi],[0 pi/2-0.2]);
x1 = -pi+0.4+x0; y1 = -0.2+y0;
line([-pi+0.4 x1],[-0.2 y1],'LineWidth',3);
x = linspace(0,pi,100);
y = 0.5*l*sin(x);
fill(x,y,'r');
point_line(-pi+0.4+x0/2,-pi+0.4+x0/2,0,-0.2+y0/2);
plot(-pi+0.4+x0/2,-0.2+y0/2,'r.','MarkerSize',16)
text(-pi+x0/2,-0.2+y0/2,'M','FontSize',12)

[xp1,yp1]=xy_change(0.5,0.5*a-0.2 ,xmin,xmax,ymin,ymax);
str_1 = '$x={l\over 2}sin(\phi)$';
text('string',str_1,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp1 yp1]);
[xp2,yp2]=xy_change(pi-0.4,-0.2,xmin,xmax,ymin,ymax);
str_2 = '$\phi$';
text('string',str_2,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp2 yp2]);
[xp3,yp3]=xy_change(0.1,a,xmin,xmax,ymin,ymax);
str_3 = '$x$';
text('string',str_3,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp3 yp3]);
[xp4,yp4]=xy_change(-pi+0.1,pi/2-0.2,xmin,xmax,ymin,ymax);
str_4 = '$a$';
text('string',str_4,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp4 yp4]);
[xp5,yp5]=xy_change(-pi+0.4+x0/2,0.3+y0/2,xmin,xmax,ymin,ymax);
str_5 = '$l$';
text('string',str_5,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp5 yp5]);
[xp6,yp6]=xy_change(-pi+0.65,0.2,xmin,xmax,ymin,ymax);
str_6 = '$\phi$';
text('string',str_6,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp6 yp6]);
[xp7,yp7]=xy_change(-pi+1.0,0.6,xmin,xmax,ymin,ymax);
str_7 = '$x$';
text('string',str_7,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp7 yp7]);
[xp8,yp8]=xy_change(-0.4,a/2,xmin,xmax,ymin,ymax);
str_8 = '${a\over 2}$';
text('string',str_8,...
    'Interpreter','latex',...
    'FontSize',16,'FontName','黑体',...
    'units','norm',...
    'position',[xp8 yp8]);
%text(-1.8,-0.3,'图7.1-1  蒲丰投针计算\pi示意图','FontSize',16);
% axis equal;
axis off;

